version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    commit-message:
      prefix: "chore: "
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      r-documentation-rs:
        patterns:
          - "rd-*"

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "ci: "
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
