//! Internal source-header extraction support.

use rd_ast::RdDocument;

/// Extract owned source paths from a recognized generation header.
pub(crate) fn extract_source_files(document: &RdDocument) -> Vec<String> {
    document
        .generation_header()
        .map(|header| {
            header
                .source_files()
                .iter()
                .map(|path| (*path).to_owned())
                .collect()
        })
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use rd_ast::{RdDocument, RdNode, RdTag};

    use super::extract_source_files;

    #[test]
    fn extracts_roxygen_source_files_as_owned_paths() {
        let document = RdDocument::new(vec![
            RdNode::Comment("% Generated by roxygen2: do not edit by hand".into()),
            RdNode::Text("\n".into()),
            RdNode::Comment("% Please edit documentation in R/whatever.R".into()),
            RdNode::tagged(RdTag::Description, None, vec![RdNode::Text("body".into())]),
        ]);

        assert_eq!(extract_source_files(&document), ["R/whatever.R".to_owned()]);
    }

    #[test]
    fn returns_no_source_files_without_a_generation_header() {
        let document = RdDocument::new(vec![
            RdNode::Comment("% ordinary comment".into()),
            RdNode::Text("\n".into()),
            RdNode::tagged(RdTag::Description, None, vec![RdNode::Text("body".into())]),
        ]);

        assert!(extract_source_files(&document).is_empty());
    }
}
