//! Roxygen2 metadata extraction
//!
//! This module provides functionality to extract metadata from Rd files
//! generated by roxygen2, including source R file paths.
//!
//! Roxygen2-generated Rd files have header comments in the following format:
//!
//! ```text
//! % Generated by roxygen2: do not edit by hand
//! % Please edit documentation in R/file1.R, R/file2.R
//! ```
//!
//! For files with many sources, the paths may span multiple lines:
//!
//! ```text
//! % Generated by roxygen2: do not edit by hand
//! % Please edit documentation in R/coord-.R, R/coord-cartesian-.R,
//! %   R/coord-fixed.R, R/coord-flip.R
//! ```

use serde::{Deserialize, Serialize};

/// Metadata extracted from roxygen2-generated Rd files.
///
/// This struct contains information about the source R files that were used
/// to generate an Rd documentation file.
///
/// # Example
///
/// ```
/// use rd_parser::RoxygenMetadata;
///
/// let metadata = RoxygenMetadata {
///     is_generated: true,
///     source_files: vec!["R/coord-map.R".to_string(), "R/coord-quickmap.R".to_string()],
/// };
///
/// assert!(metadata.is_generated);
/// assert_eq!(metadata.source_files.len(), 2);
/// ```
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct RoxygenMetadata {
    /// Whether the file was generated by roxygen2.
    ///
    /// This is `true` if the file contains the comment:
    /// `% Generated by roxygen2: do not edit by hand`
    pub is_generated: bool,

    /// Source R file paths that were used to generate this Rd file.
    ///
    /// Extracted from the comment:
    /// `% Please edit documentation in R/file1.R, R/file2.R`
    ///
    /// Paths are stored as they appear in the comment (e.g., "R/coord-map.R").
    pub source_files: Vec<String>,
}

impl RoxygenMetadata {
    /// Create a new empty `RoxygenMetadata`.
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns `true` if this Rd file has associated source files.
    pub fn has_sources(&self) -> bool {
        !self.source_files.is_empty()
    }
}

/// Marker comment indicating the file was generated by roxygen2.
const GENERATED_MARKER: &str = "Generated by roxygen2";

/// Prefix for the line containing source file paths.
const SOURCE_FILES_PREFIX: &str = "Please edit documentation in ";

/// Parse roxygen2 metadata from the header comments of an Rd file.
///
/// This function extracts metadata from the leading `%` comments before any
/// Rd content begins. It detects:
/// - Whether the file was generated by roxygen2
/// - The source R files listed in "Please edit documentation in ..." comments
///
/// # Example
///
/// ```
/// use rd_parser::parse_roxygen_comments;
///
/// let input = r#"% Generated by roxygen2: do not edit by hand
/// % Please edit documentation in R/foo.R
/// \name{foo}
/// "#;
///
/// let metadata = parse_roxygen_comments(input);
/// assert!(metadata.is_generated);
/// assert_eq!(metadata.source_files, vec!["R/foo.R"]);
/// ```
///
/// # Multi-line sources
///
/// ```
/// use rd_parser::parse_roxygen_comments;
///
/// let input = r#"% Generated by roxygen2: do not edit by hand
/// % Please edit documentation in R/coord-.R, R/coord-cartesian-.R,
/// %   R/coord-fixed.R, R/coord-flip.R
/// \name{Coord}
/// "#;
///
/// let metadata = parse_roxygen_comments(input);
/// assert!(metadata.is_generated);
/// assert_eq!(metadata.source_files.len(), 4);
/// ```
pub fn parse_roxygen_comments(input: &str) -> RoxygenMetadata {
    let mut metadata = RoxygenMetadata::new();
    let mut source_files_buffer = String::new();
    let mut in_source_files = false;

    for line in input.lines() {
        // Stop at the first non-comment line
        let trimmed = line.trim_start();
        if !trimmed.starts_with('%') {
            break;
        }

        // Remove the leading '%' and get the comment content
        let comment = trimmed.strip_prefix('%').unwrap_or("").trim_start();

        // Check for roxygen2 generation marker
        if comment.contains(GENERATED_MARKER) {
            metadata.is_generated = true;
            continue;
        }

        // Check for source files line
        if let Some(rest) = comment.strip_prefix(SOURCE_FILES_PREFIX) {
            in_source_files = true;
            source_files_buffer.push_str(rest);
            continue;
        }

        // Handle continuation lines (indented content after "Please edit documentation in")
        // Continuation lines start with whitespace after the '%'
        if in_source_files {
            let after_percent = trimmed.strip_prefix('%').unwrap_or("");
            // Check if this is a continuation (starts with whitespace)
            if after_percent.starts_with(|c: char| c.is_whitespace()) {
                source_files_buffer.push_str(after_percent.trim());
            } else {
                // Not a continuation, stop collecting source files
                in_source_files = false;
            }
        }
    }

    // Parse the collected source files
    if !source_files_buffer.is_empty() {
        metadata.source_files = source_files_buffer
            .split(',')
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();
    }

    metadata
}

#[cfg(test)]
mod tests {
    use super::*;

    // ---- RoxygenMetadata struct tests ----

    #[test]
    fn test_default() {
        let metadata = RoxygenMetadata::default();
        assert!(!metadata.is_generated);
        assert!(metadata.source_files.is_empty());
        assert!(!metadata.has_sources());
    }

    #[test]
    fn test_with_sources() {
        let metadata = RoxygenMetadata {
            is_generated: true,
            source_files: vec!["R/foo.R".to_string()],
        };
        assert!(metadata.is_generated);
        assert!(metadata.has_sources());
        assert_eq!(metadata.source_files.len(), 1);
    }

    #[test]
    fn test_json_serialization() {
        let metadata = RoxygenMetadata {
            is_generated: true,
            source_files: vec!["R/coord-map.R".to_string(), "R/coord-quickmap.R".to_string()],
        };

        let json = serde_json::to_string(&metadata).unwrap();
        assert!(json.contains("\"is_generated\":true"));
        assert!(json.contains("R/coord-map.R"));

        let parsed: RoxygenMetadata = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, metadata);
    }

    // ---- parse_roxygen_comments tests ----

    #[test]
    fn test_parse_single_source_file() {
        let input = r#"% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/grob-absolute.R
\name{absoluteGrob}
"#;
        let metadata = parse_roxygen_comments(input);
        assert!(metadata.is_generated);
        assert_eq!(metadata.source_files, vec!["R/grob-absolute.R"]);
    }

    #[test]
    fn test_parse_multiple_source_files() {
        let input = r#"% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/coord-map.R, R/coord-quickmap.R
\name{coord_map}
"#;
        let metadata = parse_roxygen_comments(input);
        assert!(metadata.is_generated);
        assert_eq!(
            metadata.source_files,
            vec!["R/coord-map.R", "R/coord-quickmap.R"]
        );
    }

    #[test]
    fn test_parse_multiline_source_files() {
        let input = r#"% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/coord-.R, R/coord-cartesian-.R,
%   R/coord-fixed.R, R/coord-flip.R, R/coord-map.R, R/coord-polar.R,
%   R/coord-quickmap.R, R/coord-radial.R, R/coord-transform.R
\docType{data}
\name{Coord}
"#;
        let metadata = parse_roxygen_comments(input);
        assert!(metadata.is_generated);
        assert_eq!(metadata.source_files.len(), 9);
        assert_eq!(metadata.source_files[0], "R/coord-.R");
        assert_eq!(metadata.source_files[8], "R/coord-transform.R");
    }

    #[test]
    fn test_parse_not_roxygen_generated() {
        // A file with comments but not roxygen2 generated
        let input = r#"% This is a hand-written Rd file
% Author: Someone
\name{manual}
\title{Manual Documentation}
"#;
        let metadata = parse_roxygen_comments(input);
        assert!(!metadata.is_generated);
        assert!(metadata.source_files.is_empty());
    }

    #[test]
    fn test_parse_no_comments() {
        let input = r#"\name{example}
\title{Example}
\description{No header comments.}
"#;
        let metadata = parse_roxygen_comments(input);
        assert!(!metadata.is_generated);
        assert!(metadata.source_files.is_empty());
    }

    #[test]
    fn test_parse_empty_input() {
        let metadata = parse_roxygen_comments("");
        assert!(!metadata.is_generated);
        assert!(metadata.source_files.is_empty());
    }

    #[test]
    fn test_parse_generated_but_no_source_files() {
        // Unusual case: roxygen2 marker but no source file info
        let input = r#"% Generated by roxygen2: do not edit by hand
\name{example}
"#;
        let metadata = parse_roxygen_comments(input);
        assert!(metadata.is_generated);
        assert!(metadata.source_files.is_empty());
    }

    #[test]
    fn test_parse_real_ggplot2_coord() {
        // Real example from ggplot2's Coord.Rd
        let input = r#"% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/coord-.R, R/coord-cartesian-.R,
%   R/coord-fixed.R, R/coord-flip.R, R/coord-map.R, R/coord-polar.R,
%   R/coord-quickmap.R, R/coord-radial.R, R/coord-transform.R
\docType{data}
\name{Coord}
\alias{Coord}
\alias{CoordCartesian}
"#;
        let metadata = parse_roxygen_comments(input);
        assert!(metadata.is_generated);
        assert_eq!(
            metadata.source_files,
            vec![
                "R/coord-.R",
                "R/coord-cartesian-.R",
                "R/coord-fixed.R",
                "R/coord-flip.R",
                "R/coord-map.R",
                "R/coord-polar.R",
                "R/coord-quickmap.R",
                "R/coord-radial.R",
                "R/coord-transform.R",
            ]
        );
    }
}
